### General parameters
SOURCE_NAME = phase_accumulator
LIBRARY_PATH = ..
EXTERNAL_SOURCES_NAME =
TESTBENCH_DIR ?= testbenches
TESTBENCH_FILE ?= $(TESTBENCH_DIR)/testbench.vhd
TESTBENCH_ENTITY ?= simulation
OUTPUT_DIR = output
STOP_TIME ?= 150us

VHDL_STD = 08

# GHDL options
OPTIONS = --std=$(VHDL_STD) \
	--workdir=$(OUTPUT_DIR)
RUN_OPTIONS = --stop-time=$(STOP_TIME) \
	--wave=$(DUMP_FILE)

### Get file names
# Extract testbench name (without path or extension)
TESTBENCH_NAME = $(notdir $(basename $(TESTBENCH_FILE)))

SOURCE_FILE = $(SOURCE_NAME).vhd
# Resolve external source paths. Expected hierarchy:
# <LIBRARY_PATH>/<external_source_name>/<external_source_name>.vhd
EXTERNAL_SOURCES_FILES := $(foreach library_name,\
	$(EXTERNAL_SOURCES_NAME),\
	$(LIBRARY_PATH)/$(library_name)/$(library_name).vhd)
ALL_VHDL_FILES = $(SOURCE_FILE) $(TESTBENCH_FILE) $(EXTERNAL_SOURCES_FILES)
WORK_CF_FILE = $(OUTPUT_DIR)/work-obj$(VHDL_STD).cf
DUMP_FILE = $(OUTPUT_DIR)/$(TESTBENCH_NAME).ghw
# Derive the default GTKWave save file (.gtkw) from the TESTBENCH_FILE path and
# name.
SAVE_FILE ?= $(patsubst %.vhd,%.gtkw,$(TESTBENCH_FILE))

### Recipes
.PHONY: all simulation elaborate run clean

all: simulation

$(WORK_CF_FILE): $(ALL_VHDL_FILES)
	@mkdir -p $(OUTPUT_DIR)
	@echo "Importing files in the work library..."
	ghdl -i $(OPTIONS) $^
	@echo "Analysis and elaboration..."
	ghdl -m $(OPTIONS) $(TESTBENCH_ENTITY)

$(DUMP_FILE): $(WORK_CF_FILE)
	@echo "Running (simulation)..."
	ghdl -r $(OPTIONS) $(TESTBENCH_ENTITY) $(RUN_OPTIONS)

# Load the GTKWave save file only if it exists. Only uses the dump file otherwise.
simulation: $(DUMP_FILE)
	@echo "Opening GTKWave..."
	gtkwave $(DUMP_FILE) $(wildcard $(SAVE_FILE))

elaborate: $(WORK_CF_FILE)

run: $(DUMP_FILE)

clean:
	@echo "Cleaning..."
	rm -f $(DUMP_FILE)
	rm -f $(WORK_CF_FILE)
	rm -f -d $(OUTPUT_DIR)
