# Before executing "make", please run this command:
#source /home/jmfriedt/openxc7/export.sh

PRJ = DDS_redpitaya
VHDL_LIBRARY_PATH = ..
VHDL_LIBRARY_NAMES = DDS LUT_sinus phase_accumulator DAC_AD9767
V_LIST = $(OUTPUT_DIR)/$(PRJ).v
CONSTR = ../ports.xdc
OUTPUT_DIR = output

VHDL_LIBRARY_FILES := $(foreach bibli_name, $(VHDL_LIBRARY_NAMES),\
	$(VHDL_LIBRARY_PATH)/$(bibli_name)/$(bibli_name).vhd)

DEVICE = zynq7
PART   = xc7z010clg400-1
DBPART = $(shell echo $(PART) | sed -e 's/-[0-9]//g')
SPEEDGRADE = $(shell echo $(PART) | sed -e 's/.*\-\([0-9]\)/\1/g')

CHIPDB_DIR ?= ../chipdb/
ifeq ($(CHIPDB_DIR),)
CHIPDB_DIR = ../chipdb/
endif

PYPY3 = pypy3

GHDL_OPT = --synth --out=verilog --no-formal --workdir=$(OUTPUT_DIR)

#YOSYS_OPT=-q -p "scratchpad -set xilinx_dsp.multonly 1"
YOSYS_OPT=-q -p "synth_xilinx -flatten -abc9 -arch xc7 -top $(PRJ); write_json $(OUTPUT_DIR)/$(PRJ).json"

.PHONY: all load verify clean

all: $(OUTPUT_DIR)/$(PRJ).bit

$(OUTPUT_DIR)/$(PRJ).v: $(PRJ).vhd $(VHDL_LIBRARY_FILES)
	# obsolete
	#yosys -m ghdl -p 'ghdl --std=08 $(VHDL_LIBRARY_FILES) $(PRJ).vhd -e $(PRJ); write_verilog $(PRJ).v'
	# new with recent ghdl
	@mkdir -p $(OUTPUT_DIR)
	@echo "Info: \tfour warnings concerning IBUFDS and BUFG not bound are normal during the execution of the next command"
	ghdl $(GHDL_OPT) $^ -e $(PRJ) > $@

$(OUTPUT_DIR)/$(PRJ).json: $(V_LIST)
	yosys $(YOSYS_OPT) $^

# The chip database only needs to be generated once
# that is why we don't clean it with make clean
$(CHIPDB_DIR)/$(DBPART).bin:
	mkdir -p $(CHIPDB_DIR)
	$(PYPY3) $(NEXTPNR_XILINX_PYTHON_DIR)/bbaexport.py --device $(PART) --bba $(DBPART).bba
	bbasm -l $(DBPART).bba $(CHIPDB_DIR)/$(DBPART).bin
	rm -f $(DBPART).bba
	
$(OUTPUT_DIR)/$(PRJ).fasm: $(OUTPUT_DIR)/$(PRJ).json $(CHIPDB_DIR)/$(DBPART).bin $(CONSTR)
	nextpnr-xilinx --chipdb $(CHIPDB_DIR)/$(DBPART).bin --xdc $(CONSTR) \
		--json $(OUTPUT_DIR)/$(PRJ).json --write $(OUTPUT_DIR)/$(PRJ)_routed.json --fasm $@

$(OUTPUT_DIR)/$(PRJ).frames: $(OUTPUT_DIR)/$(PRJ).fasm
	fasm2frames --part $(PART) --db-root $(PRJXRAY_DB_DIR)/$(DEVICE) $< > $@

$(OUTPUT_DIR)/$(PRJ).bit: $(OUTPUT_DIR)/$(PRJ).frames
	xc7frames2bit --part_file $(PRJXRAY_DB_DIR)/$(DEVICE)/$(PART)/part.yaml --part_name $(PART) \
		--frm_file $< --output_file $@

load: $(OUTPUT_DIR)/$(PRJ).bit
	openFPGALoader -c digilent_hs2 $<

verify: $(PRJ).vhd $(VHDL_LIBRARY_FILES)
	@mkdir -p $(OUTPUT_DIR)
	@echo "Importing files in the work library..."
	ghdl -i --workdir=$(OUTPUT_DIR) $^
	@echo "Analysis and elaboration... (Only four warnings concerning IBUFDS and BUFG not bound should appear)"
	ghdl -m --workdir=$(OUTPUT_DIR) $(PRJ)

clean:
	@echo "Cleaning..."
	rm -f $(OUTPUT_DIR)/$(PRJ).v
	rm -f $(OUTPUT_DIR)/$(PRJ).json
	rm -f $(OUTPUT_DIR)/$(PRJ)_routed.json
	rm -f $(OUTPUT_DIR)/$(PRJ).fasm
	rm -f $(OUTPUT_DIR)/$(PRJ).frames
	rm -f $(OUTPUT_DIR)/$(PRJ).bit
	rm -f $(OUTPUT_DIR)/work-obj93.cf
	rm -f -d $(OUTPUT_DIR)
	@echo "Info: \tCHIP DB not cleaned. You can delete manually $(CHIPDB_DIR) if needed."
