SOURCE_NAME = DAC_AD9767
TESTBENCH_NAME ?= testbench
TESTBENCH_ENTITY = simulation
STOP_TIME = 100ns

SOURCE_FILE = $(SOURCE_NAME).vhd
TESTBENCH_FILE = $(TESTBENCH_NAME).vhd
DUMP_FILE = $(TESTBENCH_NAME).ghw
SAVE_FILE ?= $(TESTBENCH_NAME).gtkw

all: verify

.PHONY: verify
verify: $(SOURCE_FILE) $(TESTBENCH_FILE)
	ghdl -a --std=08 $(SOURCE_FILE) $(TESTBENCH_FILE)

.PHONY: simulation
simulation: verify
	ghdl -r --std=08 $(TESTBENCH_ENTITY) --stop-time=$(STOP_TIME) --wave=$(DUMP_FILE)
	gtkwave $(DUMP_FILE) $(wildcard $(SAVE_FILE))

.PHONY: clean
clean:
	-rm -f $(DUMP_FILE)
	-rm -f *.cf
